<?php

/**
 * @file
 *   Drupal user and Drupal VoIP module integration.
 */

define('VOIPUSER_NUMBER_CONFIRMED', 0x0001);
define('VOIPUSER_NUMBER_ACTIVE', 0x0002);
define('VOIPUSER_NUMBER_DEFAULT', 0x0004);

/**
 * Implements hook_perm().
 */
function voipuser_perm() {
  return array(
    'Have VoIP user number',
    'Edit own VoIP user number',
    'Administer VoIP user numbers',
  );
}

/**
 * Implements of hook_menu().
 */
function voipuser_menu() {
  $items = array();

  $items['user/%user/edit/voipnumber'] = array(
    'title' => 'Phone number',
    'page callback' => 'voipuser_settings_page',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'voipuser_edit_access',
    'access arguments' => array(1),
    'tab_parent' => 'user/%/edit',
    'file' => 'voipuser.user.inc',
  );

  $items['user/%user/edit/voipnumber/add'] = array(
    'title' => 'Add number',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipuser_settings_add_form', 1),
    'type' => MENU_CALLBACK,
    'access callback' => 'voipuser_edit_access',
      // @todo and not if set and no multiple.
    'access arguments' => array(1),
    'file' => 'voipuser.user.inc',
  );

  $items['user/%user/edit/mobile/%/delete'] = array(
    'title' => 'Delete mobile number',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipuser_settings_delete_form', 1, 4),
    'type' => MENU_CALLBACK,
    'access callback' => 'voipuser_delete_access',
    'access arguments' => array(1, 4),
    'file' => 'voipuser.user.inc',
  );

  return $items;
}

/**
 * Menu access callback.
 */
function voipuser_edit_access($account) {
  return (user_edit_access($account) && user_access('Have VoIP user number', $account));
}

/**
 * Implements hook_user().
 */
function voipuser_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'load':
      return voipuser_user_load($account, $category);
    case 'insert':
    case 'update':
      return voipuser_user_save($edit, $account, $category);
    case 'view':
      return voipuser_user_view($account);
    case 'register':
      return voipuser_user_register();
    case 'delete':
      return voipuser_user_delete($account->uid);
    case 'validate':
      return;
    case 'login':
      return;
    case 'categories':
      return voipuser_user_categories();
  }
}

/**
 * hook_user() for $op = 'load'.
 */
function voipuser_user_load(&$account, $category) {
  $account->voipuser = array();
  $account->voipuser = VoipUserNumber::getNumbersFromUid($account->uid);
}

/**
 * hook_user() for $op = 'insert' || $op = 'update'.
 *
 * @todo seperate insert, update; keep common together.
 */
function voipuser_user_save(&$edit, &$account, $category) {
  print_r($account);

  if (($category == 'voipnumber' || $category == 'account') && $edit['voipnumber']) {
    $numbers = $edit['voipnumber'];
    db_query('DELETE FROM {voipuser_numbers} WHERE uid = %d', $account->uid);
    foreach ($numbers as $number) {
      $voipnumber = new VoipUserNumber($number['number'], $account->uid, $number['number_prefix'], $number['status']);
      drupal_write_record('voipuser_numbers', $voipnumber);
      $account->voipnumber[$voipnumber->getNumber()] = $voipnumber;
    }
    $edit['voipnumber'] = NULL;
  }
  else {
    db_query('DELETE FROM {voipuser_numbers} WHERE uid = %d', $account->uid);
    foreach ((array) $account->voipnumber as $number) {
      drupal_write_record($number);
    }
  }

  print_r($account);
}

/**
 * hook_user() for $op = 'view'.
 */
function voipuser_user_view($account) {
}

/**
 * hook_user() for $op = 'register'.
 */
function voipuser_user_register() {
}

/**
 * hook_user() for $op = 'delete'.
 */
function voipuser_user_delete($uid) {
  db_query('DELETE FROM {voipuser_numbers} WHERE uid = %d', $uid);
}

/**
 * hook_user() for $op = profile.
 */
function voipuser_user_categories() {
  return array(
    'voipuser' => array(
      'name' => 'voipnumber',
      'title' => t('Phone number'),
      'weight' => 10,
    ),
  );
}

/**
 * Create a new user, by phone number.
 *
 * Could optionally allow username being passed,
 * but then would need to offer a fail for existing
 * username.
 *
 * @param string|int $number
 *   Phone number to create user for.
 * @param array $options
 *   (optional) Keyed array of additional user options.
 *   'pass' => Drupal user password,
 *   'number_status' => VOIPUSER_NUMBER_status,
 *   'number_prefix' => VoipNumber type or prexix,
 *   'user_status' => Drupal user status,
 *   'mail' => e-mail address,
 *   'roles' => array of rolse to put user in,
 *   'language' => user language,
 *
 * @return int
 *   User ID.
 */
function voipuser_user_create($number, $options = array()) {
  $defaults = array(
    'pass' => user_password(8),
    'number_status' => 0,
    'number_prefix' => '',
    'user_status' => 1,
    // @todo more unique, non example.com dud e-mail.
    'mail' => $number . '@example.com',
    'roles' => ($role = variable_get('voipuser_registration_role', NULL)) ? array($role => 1) : NULL,
     // @todo set language to site default?
    'language' => '',
  );
  $options += $defaults;

  while (! $uid) {
    $voipnumber = new VoipUserNumber($number, NULL, $number_prefix, $phone_status);
    $account = user_save(NULL, array(
      'name' => variable_get('voipuser_registration_username', 'Drupal-') . mt_rand(1, db_result(db_query('SELECT MAX(uid) FROM {users}')) * 10),
      'pass' => $options['pass'],
      'mail' => $options['mail'],
      'roles' => $options['roles'],
      'status' => $options['user_status'],
      'language' => $options['language'],
      'voipnumber' => array(
        $number => array(
          'number' => $number,
          'status' => $options['number_status'],
          'number_prefix' => $options['number_prefix'],
        ),
      ),
    ));
    if ($account) {
      $uid = $account->uid;
    }
  }

  return $uid;
}

/**
 * Implements hook_voipscript_get_script_names().
 */
function voipuser_voipscript_get_script_names() {
  return array(
    'voipuser_autologin',
    'voipuser_logout',
  );
}

/**
 * Implements hook_voipscript_load_script().
 */
function voipuser_voipscript_load_script($script_name, $params = NULL) {
  switch ($script_name) {
    case 'voipuser_autologin':
    watchdog('DEBUG', 'voipuser_autologin');
      module_load_include('inc', 'voipuser', 'voipuser.script');
      if (isset($params['create'])) {
        return _voipuser_autologin_script($params['number'], $params['create']);
      }
      else {
        return _voipuser_autologin_script($params['number']);
      }
    case 'voipuser_logout':
      module_load_include('inc', 'voipuser', 'voipuser.script');
      return _voipuser_logout_script();
  }
}

/**
 * Implements hook_get_voip_numbers().
 */
function voipuser_get_voip_numbers($id, $type) {
  $numbers = array();
  switch ($type) {
    case 'user':
      $account = user_load($id);
      if (isset($account->sms_user)) {
        $number = $account->sms_user[0]['number'];
        $name = 'SMS Framework (' . $number . ')';
        $type = 'SMS Number';
        $numbers[] = new VoipNumber($number, $name, $type);
      }
      return $numbers;
      break;

    case 'uids':
      $sql = "SELECT uid FROM {sms_user} WHERE number = '" . $id . "'";
      $result = db_query($sql);
      while ($temp = db_fetch_array($result)) {
        if ($temp['uid'] != "") {
          $uids[$temp['uid']] = $temp['uid'];
        }
      }
      return $uids;
      break;
  }
}
